Add whitelisting CIDR Blocks
nscuro/traefik-plugin-geoblock pull request #44
Opened 2022-11-04 19:41 UTC by gauth-fr

I added a small feature to whitelist CIDRs block, even if they are supposed to be rejected (non-allowed country)
The provided example is the google cidr.

2022-11-04 19:44 UTC, gauth-fr commented
and that should resolve https://github.com/nscuro/traefik-plugin-geoblock/issues/22 ?

2022-11-04 20:09 UTC, nscuro requested changes
Thanks for the PR @gauth-fr! 🚀

Some minor nitpicks, then we're good to go.

2022-11-04 20:09 UTC, nscuro commented on plugin.go
> +			panic(fmt.Errorf("parse error on %q: %v", cidr, err))
Instead of `panic`king, this function should return an `error`.

2022-11-04 20:09 UTC, nscuro commented on plugin.go
> +			//break
I think the comments can be removed?

```suggestion
			return true, country, nil
```

2022-11-04 20:09 UTC, nscuro commented on plugin.go
> +	}
This is redundant and can be removed.

```suggestion
```

2022-11-04 20:29 UTC, gauth-fr commented
Sure I agree :) what should I do? (I'm quite new to git and go^^)
Change my code and commit again?

2022-11-04 20:42 UTC, nscuro commented
Oh sorry, based on your code I was assuming you're experienced! :)

Yeah, it boils down to changing your code locally according to my comments, committing and pushing your changes. The PR will be updated automatically, and we can mark my comments as "resolved". If you run into issues, I'm happy to assist. Just tell me what tools you use to work with Git, what platform (Windows, Linux, macOS) you're on, and I can guide you.

But you may notice that two of my comments have *suggested changes* in them. You can apply my suggestions using the "commit suggestion" button:

<img width="793" alt="Screenshot 2022-11-04 at 21 30 42" src="https://user-images.githubusercontent.com/5693141/200069552-8076d070-6378-4124-b23e-65702c7d1192.png">

It will create a commit for you.

2022-11-04 20:44 UTC, gauth-fr commented
Nah I learned go like 4h ago thanks to Google and stackoverflow^^
I'll give a try tomorrow, it starts to be late to geek ^^

2022-11-05 07:41 UTC, gauth-fr commented
Done!
Then i was wondering if, in case of CIDR parsing error i should really return an error or just print an error message.
At least it wouldn't block everything no?

2022-11-05 10:14 UTC, nscuro commented
> in case of CIDR parsing error i should really return an error or just print an error message.

I think that when there is a configuration error, it should be *super* obvious that something is not right. I doubt many users follow their logs, and even if they do, a warning may be easy to miss.

2022-11-05 10:16 UTC, nscuro approved these changes
Thanks again for the PR!

2022-11-05 10:16 UTC, merged

2022-11-05 10:20 UTC, gauth-fr commented
Yeah! My first approved PR^^